### ISSUE TITLE
Can't uncomment "#define SINGLEBUTTON" in LSOS 1.4. I want to use aux button.

### ISSUE THREAD

**Issue by Sligs78** [neskweek/LightSaberOS#38]
The default setting when leaving "#define SINGLEBUTTON" causes LSOS to be single button mode. When uncommenting, it gives a compile error at "Buttons.cpp" at line 260 "void mainLongPress() {". 

It gives the error message:

-----------------------------------------------------------
exit status 1
a function-definition is not allowed here before '{' token

-----------------------------------------------------------

=======================================================

I'm trying to use the aux button function because it has the lock-up sound bug fixed.

Also, how do you go down in the menu in LSOS 1.4? I tried to turn the volume down, but the only option was to go louder. I had to change it back to LSOS 1.3 to turn it down.

**Comment by Protonerd** [comment]
Please try again now, I fixed the problem.

**Comment by Sligs78** [comment]
The aux button is working now, but now there's other problems. When I hold the main button to turn it off, the DIYino resets. It does the same thing when I'm in the config menu and get to the clash color--the power resets before the clash color option shows up.

I also tried that light ignition speed suggestion in the other topic, but it only turned on the first LED and can't turn off. Same with the other numbers.

**Comment by Protonerd** [comment]
I recall you mentioned that you use 144 leds. That is too many! Unfortunately the nepixels use up a lot of dynamic RAM, and if the avr runs out of it, it resets. What you describe fits this particular error behaviour. I tried the code up to 120 leds, I do not guarantee nor recommend to use more due to unpredictable behaviour. Even if you have the full 1m of stipe, try to first reduce the count in the code to let's say 100 and try. It will work. Then you can experiment what is the highest number which will still maintain function integrity,

**Comment by Sligs78** [comment]
I just tried 100 leds and it doesn't work.

Using 144 leds didn't cause a problem for me before.
