### ISSUE TITLE
Swing Detection Issue

### ISSUE THREAD

**Issue by Vulkan1** [neskweek/LightSaberOS#41]
So ive been working though troubleshoots for a while now. Im now at the point where ive even done my own PCB cause my old board drove me nuts. So far all is good, all connections are perfect and things are where they are meant to be. 
I have an issue, I believe with, and most likely due to my accord, coding.
So im experiencing crackling, buzzing and incorrect sounds. I have all 5 sound fonts on. and checked their number count to the count on the soundconfig. I just cant figure it out. I looked at hardware and to my knowledge of software. 
as lea has said in the past, with some slight rewording.
Help me community, your my only hope.

on a more serious note, if I need to attach anything give me a buzz.

**Comment by jbkuma** [comment]
As for the buzzing.. Are you powering the sound off the Arduino? The
dfplayer should be powered directly.  If you aren't using a battery yet, it
could be a noisy power supply.

If you are getting incorrect sounds thay is most likely due to either a
Soundfont.h issue or SD card issue.  Format your card using the tool here
https://www.sdcard.org/downloads/formatter_4/

Are you running a NeoPixel blade? You may be running out of memory. If the
IDE is trying you that you are using more than around 60℅ of RAM, the pixel
blade can cause some issues. Try reducing to 3 or 4 fonts. To test, you can
simply comment out the last case in Soundfont.h and change the number of
fonts without changing the sd card.

On Feb 11, 2017 6:08 AM, "Vulkan1" <notifications@github.com> wrote:

So ive been working though troubleshoots for a while now. Im now at the
point where ive even done my own PCB cause my old board drove me nuts. So
far all is good, all connections are perfect and things are where they are
meant to be.
I have an issue, I believe with, and most likely due to my accord, coding.
So im experiencing crackling, buzzing and incorrect sounds. I have all 5
sound fonts on. and checked their number count to the count on the
soundconfig. I just cant figure it out. I looked at hardware and to my
knowledge of software.
as lea has said in the past, with some slight rewording.
Help me community, your my only hope.

on a more serious note, if I need to attach anything give me a buzz.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/neskweek/LightSaberOS/issues/41>, or mute the thread

**Comment by Vulkan1** [comment]
As for the bussing, the dfplayer Vin is connected to the 5v off the arduino. I am using apple headphones to test the sounds.
Blade type is luxeon.
And i will try out the SD formatting. That most likely will be the issue as I forgot the all important step of formatting before moving the files over, various times.

**Comment by jbkuma** [comment]
Take the dfplayer off the 5v and connect it to the battery +, that is
almost certainly the cause of your buzzing.  If you are powering via USB
right now you can either power it separately or a smoothing capacitor might
help (I haven't tried this).

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Vulkan1** [comment]
a previous problem that I never fixed in December as I wanted to work on hardware miniaturizing, the clash detection works, the swing however doesn't. now all the connections are solid I can give it a good swining and it doesn't want to make any noise. Any thoughts. 
*The MPU calibration was done with the DIYino's code so that it would save the to EPROM, however when uploading, if I don't comment: 
`devStatus = mpu.dmpInitialize_light();  // this is a ligter version of the above`
 I will get an error, 
`class MPU6050' has no member named 'dmpInitialize_light'`
could this be the source of the problem?

*so I found dmpinitialize_light() within the MPU6050h, so its there. I tried just dmpinitilize(), and it told me it was too large, as expected. So why if dmpinitialize_light is there, does it not think it is.

**Comment by Vulkan1** [comment]
okey so update, for the sake of ease I added an audio jack with quick connects, and pluged the headphones in via that. sound is perfect now. before I used my fingers to hold the wires in place, stupid me didn't think initially that the sweat on my fingers would cause the static, let alone my skin. ive updated my previous comment with the only issue im having.

**Comment by Vulkan1** [comment]
When I put heavy motion debug on, this is what im receiving.
`Q		w=nan		x=nan		y=nan		z=nan`

**Comment by Vulkan1** [comment]
This is become a working Log XD, so I turned off all but LS Info so I could do the DMPinitalise() without light, knowing it will take more space. Swing detection now works, but I take up 98% of code space now. Any ideas why I was getting the DMPInitiliaze_light() issues?

**Comment by Protonerd** [comment]
The _light version works as expected, I do not have any issues with swings. Maybe you have to run the calibration again? BTW, the only known problem with swing is when you have neopixels and want to run the Fireblade FX. IN that case I had to switch off swings, because that branch keeps creating phantom swings, due to a random() command. Root cause is in debug but not understood at all...

**Comment by Vulkan1** [comment]
sorry let me resummerlise, 
` devStatus = mpu.dmpInitialize_light(); // this is a ligter version of the above `
gives me the error of  `class MPU6050' has no member named 'dmpInitialize_light' ` when compiling.
I played around and changed it to `devStatus = mpu.dmpInitalise();` and now it works, but it takes up 98% of the drive space rather then 89%. Swings and all work now. in fact ive almost got a working sabre, I need to finish the power supply and do the LED's test before I get the luxeon. 

I wanted to know why I get that error with the "light" version of DMPInitalising.

For all the help though, I wanted to know if I could give back. ive been working on the ultrasabers free sound fonts, adding all the 2min hums to the ends making it perfect. I wanted to know if I could share that, so that people get a stock 5 different sound fonts. Am I allowed to do this or would it breach some right?

**Comment by Protonerd** [comment]
You get the error because you either did not download the newest library version for the MPU or you did, but there is a copy of the old library still somewhere on your PC and the arduino ide finds it first.

About the sound fonts, I appreciate your offer but please check with US first. I do not think they meant to share these sound fonts for free. If it came preinstalled on a board, you are not allowed to distribute them.

**Comment by Vulkan1** [comment]
That could make sense, I will dig to find this file. With IDE is it possible to bring up all the library's it uses or will I need to find it.

Also here's the page with all the sound fonts, if being their site. They are LSU files. I converted them to Wav's and then edited them for it to work with the LSOS. By the sounds of it, I can distribute them to you all for FREE, with no price. But see what you think.
http://www.ultrasabers.com/Sound-Font-p/soundfont-manual.htm

**Comment by jbkuma** [comment]
If you go in preferences and turn on "verbose output" you may see something
like this:

Multiple libraries were found for "Wire.h"
 Used: C:\[...]\packages\arduino\hardware\avr\1.6.17\libraries\Wire
 Not used: D:\[...]\Documents\Arduino\libraries\Wire

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe

**Comment by Vulkan1** [comment]
Worked perfectly, all fixed now.
About those sound files, do you think I can make a compleation of them. Otherwise I'll pull them off the movies.

**Comment by jbkuma** [comment]
Glad you got it working.  We wouldn't be able to officially share any font
without express permission from the creator and/or copyright holder.  If
you get permission from the creator you might share it on one of the FX
forum.  People always appreciate a good font that someone is willing to
share.

Jason "Kuma" Brinkerhoff
*Mad Science Workshoppe, *proprietor
http://jbkuma.com/workshoppe
